openapi: "3.0.0"
...
paths:
  /greeting/{name}:
    post:
      operationId: run.post_greeting
      responses:
        200:
          content:
            text/plain:
              schema:
                type: string
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string